### ISSUE TITLE
Suddenly stopped working in gnome 41

### ISSUE THREAD

**Issue by atrauzzi** [RensAlthuis/vertical-overview#100]
Running on Fedora 35.  Attached my external display (not running in dual display mode).

Vertical overview doesn't seem to be working at all.  I repeatedly try to initialize it (both from the gnome extensions site as well as via CLI), but no luck.

Not sure where to get any extended information about what might be going on, but happy to try stuff!

**Comment by 13r0ck** [comment]
Might be fixed by #101

**Comment by flying4fun** [comment]
Crummy.  I too am on Fedora 35.  Just the other day I did an update, and now it's no longer working.  I can't recall which version of vertical-overview I had been using prior, but figured if I cloned the latest version from github, I'd be back in business.  Unfortunately, after a clone and install, It told me that version wasn't compatible with my system.  I looked at #101 and tried that fix/branch. It didn't work either.  The error I currently am getting is
`_proto is undefined_`
thoughts/ideas?

**Comment by 13r0ck** [comment]
Gnome shell < 42 is no longer supported. Either build the older version from source, or update your system
https://github.com/RensAlthuis/vertical-overview/pull/101/commits/878fa4d0a08822f6cf454d5867ae0c0a30d0f437

**Comment by flying4fun** [comment]
Depreciated after a month!? I'd assume the number of people that use this and Gnome 42 is not very many.  After all, 42 was released only slightly over a month ago.  

Perhaps I tried the wrong branch.  Do you know which branch was the last one to work on version 41.x?

Not really interested in 1. using Pop!_OS... Meh.   And 2. Is this only supported on the bleeding edge?  That is if I understand correctly that Gnome 42 was released on the 23rd of March this year.

**Comment by 13r0ck** [comment]
https://github.com/RensAlthuis/vertical-overview/pull/101#discussion_r843546252

Yes, community projects do not come with any guarentee of support. Building on e32626976e536a0bf4e7b3e7c4d80e9b30ecebc1 may fix your issue

**Comment by flying4fun** [comment]
Yeah, I totally understand.  That's why I was trying to follow one of the previous branches.  I'm curious to know what was changed in 42 vs 41 that would break vertical-overview.  Unfortunately, for software like this (and other gnome extensions), often little changes break compatibility. 

Perhaps I still am upset and the design choices of the gnome team.

**Comment by flying4fun** [comment]
Back in business with e326269.  Thought I had tried that before.  <shrug> 

Thanks!
I'll try to remember I'll need to update again after Fedora moves to Gnome 42.

**Comment by carlwgeorge** [comment]
The easiest way to consume e326269 on Fedora 35 is to install the extension via dnf.

```
dnf install gnome-shell-extension-vertical-overview
```

That package is currently a snapshot of e326269.  I'm the maintainer, and I intend to keep it compatible with the GNOME 41 that comes with Fedora 35.  When you upgrade to Fedora 36, you'll get a version of the package that is compatible with GNOME 42 (currently f8e39b7).

**Comment by flying4fun** [comment]
Oh! fantastic. That's the way to go. Didn't know it was in the repo.Thanks!On Apr 27, 2022 9:23 PM, Carl George ***@***.***> wrote:
The easiest way to consume e326269 on Fedora 35 is to install the extension via dnf.
dnf install gnome-shell-extension-vertical-overview

That package is currently a snapshot of e326269.  I'm the maintainer, and I intend to keep it compatible with the GNOME 41 that comes with Fedora 35.  When you upgrade to Fedora 36, you'll get a version of the package that is compatible with GNOME 42 (currently f8e39b7).

**Comment by RensAlthuis** [comment]
I have released the 42 version, since most of the major distros have moved on to 42 I'm closing this one
