### ISSUE TITLE
Second monitor's workspace is incorrectly placed

### ISSUE THREAD

**Issue by RubioJr9** [RensAlthuis/vertical-overview#14]
When "Workspaces spans displays" is selected in gnome tweaks, I get the following on my second display:
![Screenshot-20210413184848-1921x1079](https://user-images.githubusercontent.com/25259698/114638114-de17dd00-9c98-11eb-8951-4c63434f4e89.png)
The workspace selector still works, but it is behind the current large workspace background.

**Comment by clwillingham** [comment]
Got a similar issue with multi-monitor. With 4 monitors active, this is what I see:
![Screenshot from 2021-04-14 00-46-33](https://user-images.githubusercontent.com/934264/114655846-057fa180-9cbb-11eb-9054-d29921df3812.png)
apart from the layout issues though, it functions quite well.

**Comment by hzhangxyz** [comment]
Same here

**Comment by CorvetteCole** [comment]
yep same here

**Comment by RensAlthuis** [comment]
Just pushed a commit that I think will solve this. Could you check if it works for you?

**Comment by RubioJr9** [comment]
It doesn't seem to change anything for me. @hzhangxyz @CorvetteCole @clwillingham are you three still seeing this issue?

**Comment by RensAlthuis** [comment]
Can you double check you pulled the latest commit?

**Comment by RubioJr9** [comment]
Yeah I have the right commit. I also tried make & make install a few times. alt+f2 then 'r' or logging out didn't either. I also disabled all of my other extensions.

**Comment by RensAlthuis** [comment]
Very strange, this is what it looks like for me now:
![image](https://user-images.githubusercontent.com/12956267/116013608-5aafa180-a631-11eb-8ab0-ba4ada3bd824.png)

Can you go to cd ~/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/
and check if ``cat workspacesView.js | grep DisplayOverride`` outputs anything? If that gives you a result the newest changes are definitely installed.

**Comment by RubioJr9** [comment]
That didn't output anything, but deleting the directory in extensions and reinstalling did the trick!

**Comment by RensAlthuis** [comment]
Ah good. Feel free to close the issue if you thinks it's fully resolved.

**Comment by RubioJr9** [comment]
![image](https://user-images.githubusercontent.com/25259698/116014079-700cd780-a601-11eb-8567-9ef5e3e458d5.png)

I'm not seeing the background on either monitor in the overview and also workspaces on the second monitor(the one on the right). I can either leave this open or make a new one.

**Comment by RensAlthuis** [comment]
Background can be enabled in the settings, I've just added that today. 
Workspaces on second monitor happens if you have enabled workspaces span displays in tweaktools. If you disable that the thumbnails disappear. Or do you prefer an option to hide the thumbnails on secondary display regardless of the tweaktools setting?

**Comment by RubioJr9** [comment]
Ah perfect. Thanks for fixing this bug. I can close this whenever, but I just want to mention it doesn't reenable the background after disabling the extension. Also, was removing the gray area around the background on purpose?

**Comment by clwillingham** [comment]
Seems to work in my setup:
![Screenshot from 2021-04-25 20-58-22](https://user-images.githubusercontent.com/934264/116015938-13151f80-a609-11eb-8f20-ffc4065120c4.png)
not sure if its intended or not, but it looks like the wallpaper only shows up in the thumbnails on the primary display and the previews on the secondary monitors appear grey.
Either way, this things awesome and I've been using it daily for the last few weeks. Also thanks for adding the thumbnail position setting.

**Comment by RubioJr9** [comment]
After my computer went to sleep and went back into it, I'm seeing it just as @clwillingham. This is minuscule and only aesthetic, but the top and bottom of the workspace is cut off on the secondary monitors.
