### ISSUE TITLE
Remove gray/grey wasted space in overview mode to show larger desktop screen.

### ISSUE THREAD

**Issue by BombJovi** [RensAlthuis/vertical-overview#15]
First and foremost -- thank you guys for developing this extension. I'm really valuing the work that you guys do.

As for this feature feature request -- is there any way to remove that flat gray/wasted space while in overview mode? To make the desktop larger? Matter of fact, would it be possible to completely replicate the design of 3.38? Because 3.38 was perfect the way it was.

Thanks guys!

**Comment by RensAlthuis** [comment]
I agree. I'd like to get the overview a lot closer to 3.38, while keeping the fancy new animations and gestures of course.
I have already attempted to make the background static again (without much luck unfortunately).

**Comment by WillNilges** [comment]
Barring that, would it be possible to expand the available space for window previews in the overview to spread out more or be bigger?

**Comment by romgrk** [comment]
@RensAlthuis have you found the commit where they removed the static background? It's probably easier to find what changed they did and try to reverse it. In the gnome-shell repo, `git log --oneline 3.38.4..40.0 | less` is useful to explore commits.

Can I also suggest that we try something like [this](https://www.reddit.com/r/gnome/comments/mtd057/in_love_with_this/)?

**Comment by RensAlthuis** [comment]
I've made an attempt at bringing back the large static background. Would you guys do me a favour and try it out for a bit? 

branch is called: `` static-workspace-background ``

**Comment by romgrk** [comment]
Working good at first glance! Before merging the branch in master I'd fix two things:
 - Shading the background image when going into overview mode
 - Adding some styles to the thumbnails container, feels a bit naked right now

**Comment by RensAlthuis** [comment]
I think this issue is solved with the latest commits so I'll close it. If you have any other suggestions or I've misinterpreted the issue feel free to open a new one!
