### ISSUE TITLE
Increase the size of the workspace thumbnails?

### ISSUE THREAD

**Issue by BombJovi** [RensAlthuis/vertical-overview#16]
If I may add another suggestion, would be to add the option to make the workspace thumbnails(? not sure what to call these) slightly larger -- while in the overview mode.

I've photoshopped a quick image of the thing that I am talking about here: 
![OverviewMode](https://user-images.githubusercontent.com/82756725/115142411-43f0c580-a007-11eb-8aef-ca9df4706d68.png)

Just to enlarge those workspace thumbnails ever so slightly would make it easier to move applications between the workspaces by mouse. I could see it being a slider or numerical value you can adjust by setting from within the extension? Is that something that could be feasible? In essence, I am all for replicating the exact design of the Desktop as it was in 3.38

Thanks!

**Comment by RensAlthuis** [comment]
I have an option in the settings that might do what you want. I called it right offset. The setting determines the distance between the workspace switcher (the center column) and the right side of the screen. If you increase the offset the thumbnails will scale up to fill the space.

**Comment by BombJovi** [comment]
Perfect! Right-offset was exactly what I was looking for! I admit, I hadn't checked this out before as I was waiting for this extension to show up on gnome's-shell-extension website before using it. (Easier to install) 

Thanks for the work you do. I'll close this issue out. By the way, do you have a libreapay account to accept donations?
