### ISSUE TITLE
Conficts with "Top Panel Workspace scroll" and "Workspace Indicator" extensions

### ISSUE THREAD

**Issue by hute37** [RensAlthuis/vertical-overview#17]
When "Vertical Overview" is enabled

* [Top Panel Workspace Scroll](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/)
* [Workspace Indicator](https://extensions.gnome.org/extension/21/workspace-indicator/)

cease to work ...

**Comment by xuhcc** [comment]
I've also had a problem with Vertical Overview + Top Panel Workspace Scroll combination.
As a temporary workaround, I patched the latter:
```patch
--- src/extension.js	2021-04-15 20:17:50.389175999 +0300
+++ src/extension.js	2021-04-15 20:17:00.681732916 +0300
@@ -92,10 +92,10 @@
 		let motion;
 		switch (event.get_scroll_direction()) {
 		case Clutter.ScrollDirection.UP:
-			motion = Meta.MotionDirection.LEFT;
+			motion = Meta.MotionDirection.UP;
 			break;
 		case Clutter.ScrollDirection.DOWN:
-			motion = Meta.MotionDirection.RIGHT;
+			motion = Meta.MotionDirection.DOWN;
 			break;
 		case Clutter.ScrollDirection.LEFT:
 			motion = Meta.MotionDirection.LEFT;

```

**Comment by RensAlthuis** [comment]
Workspace indicator seems to work for me, and I've created a pull request for Top Panel Workspace Scroll that would fix it, if the dev approves the changes this should be fixed soon.

**Comment by RensAlthuis** [comment]
The pull request has just been merged, this will be fixed with the next release of top-panel-workspace-scroll
