### ISSUE TITLE
Workspace display is not in center even left offset and right offset set to same 

### ISSUE THREAD

**Issue by guoqiyi** [RensAlthuis/vertical-overview#18]
Anyone else noticed this?

**Comment by RensAlthuis** [comment]
I noticed that it was indeed 62 pixels off center that should be fixed now. Can you check if that works for you as well?

**Comment by guoqiyi** [comment]
Thanks,I saw the latest commit to fix this,and updated it,it works!
And there is another little problem,I have a 4K monitor,so if set the offsets  too small,Workspace display is too large to show full content like the round corner and next workspace thumbnail,like this:
![Screenshot from 2021-04-25 15-38-05](https://user-images.githubusercontent.com/3457554/115985577-0976c200-a5df-11eb-97ac-f9ac893b7a73.png)
It is not a big problem because it can be solved by enlarge the offsets,but we hopes it would be perfect ,right?Anyway,thanks for your great work!

**Comment by guoqiyi** [comment]
When I set both offsets to 640px,things works perfect:
![Screenshot from 2021-04-25 16-02-16](https://user-images.githubusercontent.com/3457554/115985735-cd902c80-a5df-11eb-9062-938ce04cdffd.png)

**Comment by RensAlthuis** [comment]
I think these issues were fixed when I closed #20 so I'll close this one for now.
