### ISSUE TITLE
Top and bottom of workspace cut off on secondary monitors

### ISSUE THREAD

**Issue by no-comma** [RensAlthuis/vertical-overview#20]
![2ndmon](https://user-images.githubusercontent.com/82644961/116037839-2ef3e200-a658-11eb-92b7-ec10490370c7.png)

It also brings usability issues because the window closing button may be cut off in overview.

**Comment by RensAlthuis** [comment]
I think I've fixed this, can you verify that it works for you as well?

**Comment by no-comma** [comment]
Yes, looks like it works now.
