### ISSUE TITLE
Dash customization

### ISSUE THREAD

**Issue by no-comma** [RensAlthuis/vertical-overview#23]
Increasing the right offset increases the size of the workspace thumbnails, so would it be possible to do the same for left offset increasing the size of the dash? Or if not, adding another option to increase its size. Also an option to move the show applications button to the bottom would be nice.

**Comment by RensAlthuis** [comment]
I believe the dash size is limited by the size of the icons, there is a list somewhere that specifies a couple different sizes. Perhaps adding some larger values to that list will do the trick, I doubt will look very good but It's worth a look at least.
Option to move the show applications button is no problem, I'll add that as soon as I have some time to work on this again (unless of course make a PR before that time).

Adding an option around this line should do it:
https://github.com/RensAlthuis/vertical-overview/blob/e2eb9c27c1bea9a6ef99ac082b21be0a80ab007e/dash.js#L35
