### ISSUE TITLE
Workspaces disappear into grey nothingness, some possible ideas....

### ISSUE THREAD

**Issue by ikeofkc** [RensAlthuis/vertical-overview#3]
So currently the workspaces just kind of disappear into the grey search area 

1. I think moving the search widget to the top left where the activities button would remove the need to have that section there. ((or just removing until typing happens) 
2.  Then you can make the top bar remain black/curved at the corners. This will make the workspaces appear to flow underneath the bar.

**Comment by raindrum** [comment]
I can think of another few ways to address the issue: (a) making workspaces gradually fade to invisible as they approach the search bar, or (b) putting a full-width panel behind the search bar, such that workspaces appear to go behind the panel. I don't know how option b would interact with shell themes, though.

@ikeofkc, FYI you can use the [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection/) extension to hide the search bar until you type. It works pretty well for this.

**Comment by RensAlthuis** [comment]
Hiding the search bar until you start typing seems like the best solution out of these. But if I remember correctly the 3.38 also had the windows disappear into nothing so I'd like to keep that as default behaviour and add hiding as an option.

**Comment by raindrum** [comment]
That makes sense; I just checked and you're right, on 3.38 the workspaces simply disappear just like they do with this extension.

**Comment by ikeofkc** [comment]
> Hiding the search bar until you start typing seems like the best solution out of these. But if I remember correctly the 3.38 also had the windows disappear into nothing so I'd like to keep that as default behaviour and add hiding as an option.

The issue is that there is a static shot of a corners partially disappearing into nothingness. In gnome 3.38, it wasn't really noticeable because it was only during transitions and the background remained static. But I agree removing the search (and possibly adding a message on the top bar next to activities button that says type to search apps or something) the top bar is the best to option, although removing is much easier

**Comment by romgrk** [comment]
What do you think of getting things back to how they were in 3.38 as a starting point? Static background image, and in overview it's simply faded.

**Comment by ikeofkc** [comment]
I mean I personally like this idea, I think the classiest look is gnome 3.38 with blurred background image extension. On 3.38, the zoom out to windows is much more elegant the way the elements just slip in on the sides gracefully instead of being blasted way out.

**BUT** I also think many people were drawn to the visual flare in GNOME 40 including the peeking workspaces... so I hate to advocate a move in one direction or the other. Perhaps there's an inbetween where the other workspaces are far enough apart that they don't peek at all, but the look of seeing the whole workspace soom out is there????

Probably a good idea to poll some people to see their preference.

**Comment by RensAlthuis** [comment]
Since this issue and #15 are very similar, I think I can close both with the latest commits. I'll think about the blurry background, for now I've just added a slight fade to the background in overview. Feel free to open or reopen the issue again though.
