### ISSUE TITLE
tag versions

### ISSUE THREAD

**Issue by carlwgeorge** [RensAlthuis/vertical-overview#32]
Please tag the versions of this extension, as described in the metadata.json file.

https://github.com/RensAlthuis/vertical-overview/blob/b21d7e782281a14bd7bef6fa5c244f8e69682308/metadata.json#L10

This makes it easier for distros to package this extension and make it easily available to users.

**Comment by RensAlthuis** [comment]
Will do :+1:

**Comment by RensAlthuis** [comment]
I'll make sure to keep the tags equal with the releases on the extensions site. So I'll close this issue.
