### ISSUE TITLE
Windows turn invisible in workspace thumbnails

### ISSUE THREAD

**Issue by no-comma** [RensAlthuis/vertical-overview#41]
When dragging a window through the workspace thumbnails, if you don't move the window to another workspace it will turn invisible but still remains interactable in the thumbnails. It happens most consistently when there is only one window in that workspace and only on the primary monitor.

https://user-images.githubusercontent.com/82644961/118351623-88ab4600-b54c-11eb-81a9-8e643828d065.mp4

**Comment by bmenant** [comment]
I had the same issue, but I can confirm 5712f405fe4a3af800aeb2720d84c8690578f5a6 fixed the problem. :ok_hand:
