### ISSUE TITLE
Thumbnail wallpapers placed incorrectly on multi-monitor

### ISSUE THREAD

**Issue by no-comma** [RensAlthuis/vertical-overview#43]
If (0, 0) of the primary monitor isn't (0, 0) of the whole display setup wallpapers in the workspace thumbnails aren't placed correctly and may only be partially visible if at all. The wallpapers are also not scaled to fit the resolution of secondary monitors if their resolution is different from the primary one.

**Comment by no-comma** [comment]
Using the changes from 928008b but changing `monitorIndex` from `Main.layoutManager.primaryIndex` to `this.monitorIndex` allows for thumbnail wallpapers on multi-monitor properly and also keeps #41 from occurring.

**Comment by RensAlthuis** [comment]
I still found some issues after changing that, but I have a solution that I believe will work. Would you mind checking out ``fix_workspace_background`` and verifying if that solves it for you as well?

**Comment by no-comma** [comment]
Yep, that does solve it.
