### ISSUE TITLE
No icons in dash / dash centered on screen

### ISSUE THREAD

**Issue by kmoad** [RensAlthuis/vertical-overview#44]
With "override dash" set to false, I don't see the normal dash in the overview. I see app running indicators, but no icons. Clicking on the areas where the icons would be has no effect.

In the app grid, the dash is vertically centered. Running app icons are in the correct place.

I was expecting to see the regular dash.

## Running
vertical-overview: latest from extensions.gnome.org as of 2021/05/17
Fedora 34
Gnome 40.1.0
Default theme and icons

## Overview

![overview](https://user-images.githubusercontent.com/19417207/118574789-2a9c7f80-b753-11eb-8b40-161b4ca4f4cd.png)

## App Grid

![appgrid](https://user-images.githubusercontent.com/19417207/118574788-2a03e900-b753-11eb-9e28-bb683feec25b.png)

## vertical-overview settings

![settings](https://user-images.githubusercontent.com/19417207/118574862-56b80080-b753-11eb-8868-057110634e08.png)

**Comment by no-comma** [comment]
Have you tried installing from source? I believe this is just a problem with the version on GNOME Extensions being outdated.

**Comment by RensAlthuis** [comment]
Yeah, this is something I have fixed but isn't on release yet. I was hoping to add in the gesture rework before I release a new version. But perhaps I should just do that earlier.

**Comment by kmoad** [comment]
Installing from source worked. Thanks!
