### ISSUE TITLE
If used with dash-to-panel, parts of the dock are still present even if there should not be anything on the left side

### ISSUE THREAD

**Issue by redgryphon** [RensAlthuis/vertical-overview#46]
As stated in the title I use [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel). Right now there is still a remnant of the dock on the left side when the overview is opened. While I think it is pretty clear what the problem is, an image speaks more than words.
![vertical-overview-bug](https://user-images.githubusercontent.com/74600987/119236136-1501ce00-bb36-11eb-8e5b-6090ea74074f.png)

**Comment by kmoad** [comment]
This is likely related to #44

**Comment by RensAlthuis** [comment]
This is working correctly in source as long as you switch off 'override dash'. 
PS: I am about to add an extra fix for dash-to-panel settings as well as a fix for dash to panel on the left side.

**Comment by RensAlthuis** [comment]
This is now fixed with the latest release as well.
