### ISSUE TITLE
When activating Overview via the Hot Corner, changing Workspaces with the mouse scroll wheel only works on 2nd Input

### ISSUE THREAD

**Issue by duartec3000** [RensAlthuis/vertical-overview#48]
Thank you so much for this project, it's a real life saver for some of us, I will be posting some small papercuts like the below going forward to help out the best I can and hopefully we will have a solid vertical overview in no time. Thanks again!

## Expected Behavior
- When activating Overview via the **Hot Corner**, changing Workspaces with the mouse scroll wheel is immediate / instant / at first Input. 
- Expected behaviour can also be experienced when activating the Overview via the **Super key**, Workspace changes instantly at the first dent / slight movement of the mouse scroll wheel.

## Actual Behavior
- When activating Overview via the **Hot Corner**, changing Workspaces with the mouse scroll wheel only works on the 2nd Input / 2nd dent of a modern mouse scroll wheel, which makes the Overview seem like it is graphically lagging but it is not.

## Steps to Reproduce the Problem

  1. Activate the Overview via the Hot Corner top left
  2. Slightly scroll with your mouse up/down  (depending on you configuration)
  3. Notice that nothing happens and slightly **scroll again**
  4. Your Workspace changes up or down

## Specifications

  - Version: Vertical Overview extension built from Git on 24/05/2021 20:00 CET
  - Platform: Gnome 40
  - Subsystem: Arch Linux (current)

**Comment by tengwar** [comment]
This issue is also present in the vanilla Gnome Shell. Try disabling the extension and you'll see. You could report it at Gnome's Gitlab.

**Comment by duartec3000** [comment]
@tengwar Thank you for the heads up, when I installed GNOME 40 I also immediately installed the vertical overview extension so I never used GNOME 40 in its default form, still should have cross checked but anyway I'm cancelling this little bug and lesson learned!

**Comment by duartec3000** [comment]
Issue to be opened in Gnome Shell Gitlab as it is not caused by the Vertical Overview Extension.
