### ISSUE TITLE
More than one UUID given

### ISSUE THREAD

**Issue by soloturn** [RensAlthuis/vertical-overview#62]
thank you for this extension! i tried to download and install - for me it gives:

```
> gnome-extensions --version
40.3

> gnome-extensions list -d
vertical-overview@RensAlthuis.github.com
  Name: Vertical overview
  Description: Bringing back vertically stacked workspaces
  Path: /home/rt/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com
  URL: 
  Original author: rens.althuis@gmail.com
  Version: 6
  State: INITIALIZED

> gnome-extensions enable gnome-extensions enable vertical-overview\@RensAlthuis.github.com
gnome-extensions: More than one UUID given

Usage:
  gnome-extensions enable [OPTION…] UUID
```

what might be the reason?

**Comment by RensAlthuis** [comment]
I expect you've solved this issue by now, sorry for the late reply. Haven't worked on this extension for a while.
Anyway it looks like you typed `gnome-extensions enable` twice.
`gnome-extensions enable gnome-extensions enable vertical-overview\@RensAlthuis.github.com`
should be:
`gnome-extensions enable vertical-overview@RensAlthuis.github.com`
