### ISSUE TITLE
Dock and Workspace Thumbnails Transition Animation

### ISSUE THREAD

**Issue by Srijan1214** [RensAlthuis/vertical-overview#68]
First of all,

this is an amazing project and is very helpful for me and many other users.

I was wondering if there were any plans to have a slight transition animation for the dock and the "side workspaces preview thumbnails" when we switch to overview? This used to be the behavior in Gnome shell 3.38 where there used to be a slight sliding animation for both the docks and the thumbnails.

Right now, the dock and thumbnails are static when we switch from and to the workspaces.

**Comment by RensAlthuis** [comment]
Yeah, I'd like to add an option for this eventually.

**Comment by Srijan1214** [comment]
Awesome
