### ISSUE TITLE
Use vignette for static background

### ISSUE THREAD

**Issue by no-comma** [RensAlthuis/vertical-overview#70]
In my opinion the current approach of changing the opacity of the overview background with static background doesn't look very good, particularly when the scaling workspaces are hidden. I think doing something like this makes it look much better and more in line with 3.38:
```
let bgManager = new Background.BackgroundManager({
    monitorIndex: monitor.index,
    container: Main.layoutManager.overviewGroup,
    vignette: true,
});

bgManager._fadeSignal = Main.overview._overview._controls._stateAdjustment.connect('notify::value', (v) => {
    bgManager.backgroundActor.content.vignette_sharpness = Util.lerp(0, 0.5, Math.min(v.value, 1));
    bgManager.backgroundActor.content.brightness = Util.lerp(1, 0.5, Math.min(v.value, 1));
});
```
Screenshots for comparison.
![comparison](https://user-images.githubusercontent.com/82644961/132476123-6570e8d5-edc4-4d54-80a6-2d4a692dfa44.png)
What do you think?

**Comment by Techwizz-somboo** [comment]
Looks way better! Adding your changes to my copy.
