### ISSUE TITLE
Gnome 41 support?

### ISSUE THREAD

**Issue by thankjura** [RensAlthuis/vertical-overview#72]
![image](https://user-images.githubusercontent.com/2144212/135092507-67f64428-f9f6-4da5-a0f1-dc4411ccd519.png)

**Comment by paulodiovani** [comment]
Probably just need to change the supported versions at https://github.com/RensAlthuis/vertical-overview/blob/master/metadata.json#L5-L7

**Comment by thankjura** [comment]
Works on fedora 35 (virtualbox x11)
![image](https://user-images.githubusercontent.com/2144212/135108905-799d66be-0a11-42e2-97cb-630b61cdeb12.png)

**Comment by RensAlthuis** [comment]
Yeah, it should mostly work with a version change. I'm just trying to work out one little issue, then I'll release a new version on the extension site as well.

**Comment by RensAlthuis** [comment]
Done, new release was just approved :+1:
