### ISSUE TITLE
Gnome crashes when locking while in fullscreen mode

### ISSUE THREAD

**Issue by Peeze** [RensAlthuis/vertical-overview#75]
The extension works perfectly, but when it is enabled I experience this bug: When the screen is locked while an application in the active workspace is in fullscreen mode, the desktop session crashes and gdm restarts.
I tried it with different applications in fullscreen mode (Firefox, Terminal, Document Viewer), the same always happens. It doesn't matter whether I lock the screen manually or it is locked because of inactivity.
Once I disable the extension, I can lock and unlock the screen without a problem.
I'm running Gnome 40.4.0 with Wayland on Arch Linux.

**Comment by no-comma** [comment]
The cause for this appears to have to do with the style applied to the top bar with "visible panel in overview." When I turned that off the crash doesn't occur. Adding `Main.panel.remove_style_class_name("vertical-overview");` to `disable()` in `extension.js` sometimes seems to prevent the crash even with the setting on and sometimes not, I don't know why.

**Comment by Peeze** [comment]
Solves the problem for me, too. Thank you!
