### ISSUE TITLE
Weird behavior of other extension when enabled

### ISSUE THREAD

**Issue by ismaail** [RensAlthuis/vertical-overview#9]
After getting [dash-to-dock](https://github.com/ewlsh/dash-to-dock/tree/ewlsh/gnome-40) to work in GNOME 40,

when I enable **vertical-overview**, dash-to-dock gets smaller & changes orientation (see video).

https://user-images.githubusercontent.com/4411670/114109989-629be180-98ce-11eb-81dc-dbd0a472aee9.mp4

I'm not sure this is **vertical-overview** issue.

**Comment by romgrk** [comment]
Intentional behavior, the extension is moving the dash.

**Comment by RensAlthuis** [comment]
Thanks for the report, this extension is indeed overwriting the dash behaviour. I'm about to add a toggle to completely ignore the dash allowing other extensions to properly manipulate it. You can expect it some time this weekend (I hope).

**Comment by RensAlthuis** [comment]
@ismaail This should be fixed now, if you pull the latest changes and look in vertical-overviews settings there should be switch you can turn off to ignore the dash.

*(don't forget to recompile the schemas after pulling the latest commit)* 
`glib-compile-schemas $HOME/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/schemas `

**Comment by ismaail** [comment]
@RensAlthuis Thank you

I pulled last comit and run `glib-compile-schemas`.

the **dash-to-dock** no longer changes orientation, but still it gets smaller.

![Screenshot from 2021-04-11 02-17-52](https://user-images.githubusercontent.com/4411670/114289029-9876cc80-9a6c-11eb-9517-7f6a7c7dca64.png)

**Comment by RensAlthuis** [comment]
Can you check if you are on the latest commit? I pushed a second one fixing the shrinking issue shortly after the first one.

**Comment by ismaail** [comment]
@RensAlthuis the latest commit f98f2333 solves the issue.

![Screenshot from 2021-04-11 02-32-25](https://user-images.githubusercontent.com/4411670/114289273-85fd9280-9a6e-11eb-928e-2ab2e13f60e6.png)
