### ISSUE TITLE
Not compatible with gnome 42

### ISSUE THREAD

**Issue by thankjura** [RensAlthuis/vertical-overview#98]
after update gjs to 1.71.1

`JS ERROR: Extension vertical-overview@RensAlthuis.github.com: TypeError: GObject_Object.prototype.[__GObject__hook_up_vfunc] called on incompatibl>
                                                  hookVfunc@/home/jura/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/util.js:9:35
                                                  overrideProto@/home/jura/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/util.js:31:26
                                                  override@/home/jura/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/overviewControls.js:35:75
                                                  enable@/home/jura/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/extension.js:26:30
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:180:32
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:364:26
                                                  _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:604:18
                                                  collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                                  _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:583:19
                                                  _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:610:18
                                                  _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:630:14
                                                  init@resource:///org/gnome/shell/ui/extensionSystem.js:54:14
                                                  _initializeUI@resource:///org/gnome/shell/ui/main.js:282:22
                                                  start@resource:///org/gnome/shell/ui/main.js:162:5
                                                  @resource:///org/gnome/shell/ui/init.js:6:17
`

I think it's related https://github.com/GNOME/gjs/commit/e74701596c2ff9880cd39289b9649bb490951091

**Comment by 13r0ck** [comment]
#101 fixes the specific issue listed above. Gnome 42 might break other things though

**Comment by stdevPavelmc** [comment]
I support that request

Just installed it manually from this repo on Ubuntu Jammy develop branch with Gnome 42 and it does not work.

**Comment by vulcainman** [comment]
I confirm that #101 fixes the issue on Gnome 42 (Debian  bookworm). IMHO, it should be merged as soon as possible.

**Comment by vulcainman** [comment]
After some times, I've noticed minor issues with workspace zone (I've 2 monitors). On the second monitor, the workspace zone is broken (see screenshot attached) and replaced by a blue dot. I've also noticed that, the first monitor's workspace zone encounters the same issue after a session lock. The first monitor workspace zone can be restored by a shell restart.

![Screenshot from 2022-03-31 09-51-47](https://user-images.githubusercontent.com/60341755/161005834-fc9927f5-883e-4b2c-8e5e-859dd4cff765.png)

**Comment by JonathanHolvey** [comment]
Another issue is that the left and right offset options aren't working as expected. It's difficult to explain in words what's going on, so here's a diagram:

![offsets](https://user-images.githubusercontent.com/10114731/161218292-0c65f134-27cf-4d36-b254-9a7cbfb0fba1.png)

**Comment by jm-duke** [comment]
Commit [2127222b](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/2127222b39c763d2f018ecd03e4d6abdc995d1b0) breaks the addon - fadeInDesktop() and fadeOutDesktop() are considered deprecated. Removing both functions from the code works fine on my end:

```
diff --git a/overviewControls.js b/overviewControls.js
index 6b6f6f9..8a3073c 100644
--- a/overviewControls.js
+++ b/overviewControls.js
@@ -335,8 +335,6 @@ var ControlsManagerOverride = {
 
         this._searchController.prepareToEnterOverview();
         this._workspacesDisplay.prepareToEnterOverview();
-        if (!this._workspacesDisplay.activeWorkspaceHasMaximizedWindows())
-            Main.overview.fadeOutDesktop();
 
         this._stateAdjustment.value = ControlsState.HIDDEN;
 
@@ -367,8 +365,6 @@ var ControlsManagerOverride = {
         this._ignoreShowAppsButtonToggle = true;
 
         this._workspacesDisplay.prepareToLeaveOverview();
-        if (!this._workspacesDisplay.activeWorkspaceHasMaximizedWindows())
-            Main.overview.fadeInDesktop();
 
         this._stateAdjustment.ease(ControlsState.HIDDEN, {
             duration: Overview.ANIMATION_TIME,
```

**Comment by vitaminace33** [comment]
Manjaro bundles version 8, therefore I hace to manually install the current master version f8e39b79d05f292cfd97d568f20d4a92ca2bea5a. However, it does not work properly, the dash is missing.

**Comment by lgg** [comment]
@JonathanHolvey for me it seems like this:
![image](https://user-images.githubusercontent.com/12018713/168448930-ba83ba61-1aec-4101-b5b5-cbfb59544be0.png)

**Comment by JPGlaser** [comment]
Do we have any status on a version getting released @RensAlthuis for Gnome 42 (Ubuntu Jelly LTS)? These horizontal workspaces are diving me up the walls.

~ Joe G.

**Comment by 13r0ck** [comment]
@RensAlthuis can this be closed because of #101 ?

**Comment by RensAlthuis** [comment]
Ah yeah this has been fixed. The extension is fully compatible with 42. I just haven't published on the gnome website.

**Comment by vitaminace33** [comment]
I confer f8e39b79d05f292cfd97d568f20d4a92ca2bea5a does works on Manjaro as of today. A Gnome Shell restart (alt+F2, restart) might be required. This could be added to the instructions.

**Comment by duartec3000** [comment]
@RensAlthuis ༼ つ ◕_◕ ༽つ Take all my energy ༼ つ ◕_◕ ༽つ make point release for us plebs, will donate again!

**Comment by RensAlthuis** [comment]
I've made a new release, @duartec3000 there is absolutely no need to donate again :stuck_out_tongue: but I appreciate the sentiment.

**Comment by real-or-random** [comment]
> @JonathanHolvey for me it seems like this:
> Screenshots
> 
> ![image](https://user-images.githubusercontent.com/12018713/168448993-510788bf-9212-4cf9-a571-d416c66c7469.png)
> 
> ![image](https://user-images.githubusercontent.com/12018713/168448930-ba83ba61-1aec-4101-b5b5-cbfb59544be0.png)

I have the same issue on a 4k screen. The main thing overlaps the thumbnails.

**Comment by thankjura** [comment]
> I have the same issue on a 4k screen. The main thing overlaps the thumbnails.

this patch works for me:
`--- overviewControls.js	2022-05-25 01:48:30.289432837 +0300
+++ /home/jura/.local/share/gnome-shell/extensions/vertical-overview@RensAlthuis.github.com/overviewControls.js	2022-05-23 21:20:38.400741149 +0300
@@ -120,9 +120,8 @@
 }
 
 var ControlsManagerLayoutOverride = {
-    _computeWorkspacesBoxForState(state, workAreaBox, searchHeight, dashHeight, thumbnailsHeight) {
+    _computeWorkspacesBoxForState(state, workAreaBox, startY, searchHeight, leftOffset, rightOffset) {
         const workspaceBox = workAreaBox.copy();
-        const [startX, startY] = workAreaBox.get_origin();
         const [width, height] = workspaceBox.get_size();
         const { spacing } = this;
         const { expandFraction } = this._workspacesThumbnails;
@@ -142,10 +141,10 @@
         case ControlsState.WINDOW_PICKER:
         case ControlsState.APP_GRID:
             workspaceBox.set_origin(
-                this.leftOffset + spacing,
+                leftOffset + spacing,
                 startY + searchHeight + spacing * expandFraction);
             workspaceBox.set_size(
-                width - this.leftOffset - this.rightOffset - (spacing * 2),
+                width - leftOffset - rightOffset - (spacing * 2),
                 height - startY - (searchHeight + spacing * expandFraction) * 2);
             break;
         }
`

**Comment by real-or-random** [comment]
Nice, that patch works for me, too. Can you open a PR?
